interfaces/utils.go
interfaces/utils_test.go

In utils, checks were provided for sending messages back and forth, but not for valid query paths. Add this check to prevent hitting AppEngine with wrong requests which can now be validated in advance.

interfaces: Add Query Validation methods

---

client/appengine.go
interfaces/utils.go
interfaces/utils_test.go

This also changes the validation semantics for Aggregates, ensuring we can keep a consistent approach everywhere from 1.0 onwards.

appengine: Add support for sending data to APIs

---

interfaces/astarte_interface.go
interfaces/astarte_interface_test.go
interfaces/utils.go
interfaces/utils_test.go

Go has very bad support for enums, but we managed to make it even worse. Use string-based enums and remove dangerous string constant duplication, and unify validation approach through IsValid(). This also fixed some bugs in JSON parsing.

interfaces: Use string enums

---

client/realm_management.go
interfaces/astarte_interface.go
interfaces/astarte_interface_test.go

Given that interface unmarshaling is completely unreliable when it comes to setting defaults,
add a function to parse interfaces and discourage any kind of json.Unmarshaling by itself.

interfaces: Add ParseInterface methods

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yaml
.golangci.yml
client/api_types.go
client/appengine.go
client/appengine_devices.go
client/appengine_groups.go
client/appengine_internal.go
client/astarte.go
client/housekeeping.go
client/paginator.go
client/pairing.go
client/realm_management.go
interfaces/astarte_interface_test.go
interfaces/utils_test.go

This PR does two main things:
* Vastly improves all the client module by ensuring that we don't need to create an enclosed struct for each return type, but we rather use json.Decoder in a clever way. As a side effect, we now also close correctly all return payloads.
* Integrates golangci-lint and closes any pending issue within the codebase.

Improve codebase quality, introduce golangci-lint

---

client/api_types.go
client/appengine_devices.go

To keep coherency in terminology replace device metadata with device attributes.

Replace device metadata with device attributes

---

CHANGELOG.md
client/appengine_devices.go

- When dealing with a single device attribute use the singular. Use the plural otherwise.
- Update the changelog.

Fix Attributes naming + update changelog

---

interfaces/astarte_interface.go
interfaces/astarte_interface_test.go

When parsing an Astarte interface, ensure that required fields are valid.

Interfaces: add validations for required fields

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yaml
README.md
go.mod

Go 1.13 is no more supported. Bump Go to a supported version.

Upgrade Go to 1.17

---

misc/device_id.go

Use standard Astarte naming for Device ID generation functions as discussed [here](https://github.com/astarte-platform/astarte-device-sdk-python/pull/19#discussion_r848167040), instead of current ad-hoc naming.
Deprecate the `GenerateNamespacedAstarteDeviceID` function, but leave it for compatibility.

Misc: standardize device ID generation naming

---

client/housekeeping_data.go

`ioutil` module has been deprecated with Go 1.16. Replace it with `io` and/or `os`, as suggested by Go guidelines.

Remove `ioutil` dep

---

interfaces/astarte_interface.go
interfaces/astarte_interface_test.go

Use the same pattern as `client.withPrivateKey`, i.e. type constraints on the argument and check if the input is a file path or actual content.
Close #32.

Interface parsing: provide a generic convenience function

---

astarteservices/astarte_service_type.go
auth/token.go
client/appengine_groups.go
client/appengine_internal.go
client/client.go
deviceid/deviceid.go

Split the package in three, more coherent parts:
- `auth` (JWT and such);
- `deviceid` (id generation and validation);
- `astarteservices` (useful constants to represent Astarte services).
Close #31.

 Unpack `misc` package

---

client/housekeeping.go

A typo in the `newRealmRequestBuilder` struct prevented it from being correctly converted to JSON, resulting in an empty payload when creating a realm. Fix it.

Housekeeping client: create valid Realm payload

---

client/client.go

returned values are deep-copied so as not to allow mutation.

Client: add methods to retrieve services URL

---

client/client.go

Fix a nil-pointer exception in the unfortunate case no URL is set.

Client: expose URLs, for real

---

client/appengine_stream.go

The AutodiscoverDeviceIdentifier type is not sufficient for properly building a valid request URL. Then, use the actual device identifier type.

Use the actual device identifier type when setting an URL

---

CHANGELOG.md
client/appengine_data.go
client/data.go

When Raw is called for responses whose structure include a paginator, the state of that paginator must be updated. To do so, compute the page state without losing the content of the response's body.

Fix Raw for responses with a paginator

---

CHANGELOG.md
client/http.go
client/realm_management.go
client/realm_management_test.go

Issue: https://github.com/astarte-platform/astartectl/issues/192

Update InstallInterface and UpdateInterface

---

interfaces/utils.go
interfaces/utils_test.go

Binaryblob and binaryblob arrays were base64-encoded twice (during the payload normalization step and during the json serialization of the payload). Thus, ensure that data is encoded just once. 
Contextually, update the tests.

Fix the base64-encoding of binaryblobs when sending data 

---

CHANGELOG.md
client/housekeeping.go

An extra layer of quotes caused a malformed request, leading to the impossibility of creating a realm when a network topology strategy is set. Thus, remove the extra quotes.

Fix: allow the creation of a realm when using network topology strategy

---

CHANGELOG.md
client/housekeeping.go

An extra layer of quotes caused a malformed request, leading to the impossibility of creating a realm when a simple strategy is set. Thus, remove the extra quotes.

Fix simple strategy option

---

triggers/astarte_trigger.go
triggers/astarte_trigger_test.go

This pr enable validation on triggers json via function "ParseTriggerFrom" and "ParseTrigger".
Check is based on official astarte documentation, resulting in the following structure schema:
```
{ 
"name" -> string, not null
"action"-> {
"http_url" -> string nullable
"http_method" -> enum [POST, GET, PUT, PATCH ecc] nullable
"http_static_headers" -> json
"ignore_ssl_errors" ->  bool default false
}
"simple_triggers array" -> one element [
{
"type" -> enum [data_trigger,device_trigger],
(only device_trigger)
"on" -> device_trigger_type enum [device_connected,device_disconnected,device_error]
"device_id" -> id of a device OR "*", nullable    |> mutually exclusive
"group_name"-> group of devices nullable         |> mutually exclusive
(only data_trigger)
"on" ->data_trigger_type enum …
```

Trigger validation

---

triggers/astarte_trigger.go

Fix parse multiline HTTPHeaders 
Fix validation for nil KnownValue  when ValueMatchOperator equal to "*"

Trigger validation: fix some corner cases

---

interfaces/utils.go

Add LongIntegerArray slice processing to interface utils
Resolves last point of https://github.com/astarte-platform/astartectl/issues/239

Add LongIntegerArray slice processing to interface utils

---

interfaces/astarte_interface.go
triggers/astarte_trigger.go

Changes error handling moving the error generation inside the function, and then just bubble up, instead of the old system where the error was rewritten

Validation error handling

---

CHANGELOG.md
client/appengine_data.go

Fix the parsing of device aliases, which are to be parsed in the same way as attributes.
See https://github.com/astarte-platform/astartectl/issues/275.

Device aliases are a map, not an array
